// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brvqiasntmzbvgxqgvxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJydnFpYXNudG16YnZneHFndnhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDgzMzUsImV4cCI6MjA2MDQ4NDMzNX0.lS_V8r31YDy6ieCXBLGoinzBg_JG9vPuMdqzpzsQ6mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);